
name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Delete previous image
      run: docker rmi demo-cicd:latest
    - name: Pull Docker image
      run: sudo docker pull fabrice7891/demo-cicd:latest
    - name: Delete Old docker container
      run: sudo docker rm -f demo-cicd-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name demo-cicd-container fabrice7891/demo-cicd
