
name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Delete previous image
      run: sudo docker rmi newrepo || true
    - name: Pull Docker image
      run: sudo docker pull fabrice7891/newrepo:latest
    - name: Delete Old docker container
      run: sudo docker rm -f newrepo-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name newrepo-container fabrice7891/newrepo
